name: Static Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and push to static repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "diysnist-static/mavka-playground-website"
          path: "dist"
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p olddist
          cp -a dist/.git dist/CNAME olddist
          npm ci
          npm run build-only
          cp -a olddist/.git CNAME dist
          cd dist
          git config --local user.name "КДБ"
          git config --local user.email "prykhozhdenko@gmail.com"
          git add .
          git commit -m "🧬"
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: "dist"
          repository: "diysnist-static/mavka-playground-website"
          ssh: true
          github_token: ${{ secrets.SSH_DEPLOY_KEY }}
